### ISSUE TITLE
SIGSEGV: govips

### ISSUE THREAD

**Issue by y3ti** [imgproxy/imgproxy#1164]
Hello,

IMGPROXY started crashing from time to time after upgrading to the new version (v3.18.0). For example, near 2023-06-15T23:26:08Z I saw in the logs:

```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x7f950633e074]

runtime stack:
runtime.throw({0x24cdba6?, 0x10?})
        /usr/local/go/src/runtime/panic.go:1047 +0x5d fp=0x7f94dda01ee0 sp=0x7f94dda01eb0 pc=0x43e81d
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:821 +0x3e9 fp=0x7f94dda01f40 sp=0x7f94dda01ee0 pc=0x454d49

goroutine 4581247 [syscall, locked to thread]:
non-Go function
        pc=0x7f950633e074
non-Go function
        pc=0x7f950633fb1a
non-Go function
        pc=0x7f9507369ea2
non-Go function
        pc=0x7f95072777ec
non-Go function
        pc=0x7f9507277e7f
non-Go function
        pc=0x7f9507342f88
non-Go function
        pc=0x7f950734ee47
runtime.cgocall(0x1e162b0, 0xc002628fb8)
        /usr/local/go/src/runtime/cgocall.go:157 +0x5c fp=0xc002628f90 sp=0xc002628f58 pc=0x40ac9c
github.com/imgproxy/imgproxy/v3/vips._Cfunc_vips_resize_go(0x7f94d805d440, 0xc0073147d0, 0x3fd1745d1745d175, 0x3fd1745d1745d175)
        _cgo_gotypes.go:1245 +0x4c fp=0xc002628fb8 sp=0xc002628f90 pc=0x1db666c
github.com/imgproxy/imgproxy/v3/vips.(*Image).Resize.func1(0xc002629068?, 0x1e03436?, 0x3fd1745d1745d175, 0x3fd1745d1745d175)
        /app/vips/vips.go:526 +0x95 fp=0xc002629000 sp=0xc002628fb8 pc=0x1dbfeb5
github.com/imgproxy/imgproxy/v3/vips.(*Image).Resize(0x0?, 0x0?, 0xc0073147a0?)
        /app/vips/vips.go:526 +0x4f fp=0xc002629050 sp=0xc002629000 pc=0x1dbfcef
github.com/imgproxy/imgproxy/v3/processing.scale(0x29b8138?, 0xc007a190b0?, 0xc0025ac480?, 0xc0017cd440?)
        /app/processing/scale.go:19 +0x9d fp=0xc002629078 sp=0xc002629050 pc=0x1e06f7d
github.com/imgproxy/imgproxy/v3/processing.pipeline.Run({0x3b22660, 0x11, 0x0?}, {0x29b8138, 0xc007a190b0}, 0xc002629230?, 0xc0025ac480, 0x3000106?)
        /app/processing/pipeline.go:55 +0x1e3 fp=0xc002629150 sp=0xc002629078 pc=0x1e04843
github.com/imgproxy/imgproxy/v3/processing.ProcessImage({0x29b8138, 0xc007a190b0}, 0xc0017cd440, 0xc0025ac480)
        /app/processing/processing.go:313 +0x5d4 fp=0xc002629378 sp=0xc002629150 pc=0x1e06514
main.handleProcessing.func3({0x29b8138, 0xc007a190b0}, 0xc0026296b0?, 0xc002629750?)
        /app/processing_handler.go:421 +0x74 fp=0xc0026293e0 sp=0xc002629378 pc=0x1e11d54
main.handleProcessing({0xc008913458, 0x15}, {0x29b61d0, 0xc001846700}, 0xc002ac2500)
        /app/processing_handler.go:422 +0x156b fp=0xc002629840 sp=0xc0026293e0 pc=0x1e119ab
main.withCORS.func1({0xc008913458?, 0x29b61d0?}, {0x29b61d0?, 0xc001846700?}, 0x100?)
        /app/server.go:112 +0x20e fp=0xc0026298c8 sp=0xc002629840 pc=0x1e136ee
main.withPanicHandler.func1({0xc008913458?, 0xc007a190b0?}, {0x29b61d0?, 0xc001846700?}, 0x0?)
        /app/server.go:163 +0x8e fp=0xc002629940 sp=0xc0026298c8 pc=0x1e13aee
main.withMetrics.func1({0xc008913458, 0x15}, {0x29b61d0?, 0xc001846700?}, 0xc002ac2400)
        /app/server.go:101 +0x16f fp=0xc0026299b8 sp=0xc002629940 pc=0x1e133cf
github.com/imgproxy/imgproxy/v3/router.(*Router).ServeHTTP(0xc0002a0ea0, {0x29b61d0, 0xc001846700}, 0x470b8e?)
        /app/router/router.go:101 +0x53d fp=0xc002629ad0 sp=0xc0026299b8 pc=0x1dcee9d
net/http.serverHandler.ServeHTTP({0xc002b28810?}, {0x29b61d0, 0xc001846700}, 0xc002ac2300)
        /usr/local/go/src/net/http/server.go:2936 +0x316 fp=0xc002629b80 sp=0xc002629ad0 pc=0x7271d6
net/http.(*conn).serve(0xc007950ea0, {0x29b8170, 0xc00015ea20})
        /usr/local/go/src/net/http/server.go:1995 +0x612 fp=0xc002629fb8 sp=0xc002629b80 pc=0x722bb2
net/http.(*Server).Serve.func3()
        /usr/local/go/src/net/http/server.go:3089 +0x2e fp=0xc002629fe0 sp=0xc002629fb8 pc=0x727b2e
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc002629fe8 sp=0xc002629fe0 pc=0x472d61
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:3089 +0x5ed
```

but IMGPROXY still was processing requests during next ~50 minutes, and next it stopped accepting new connections:

<img width="636" alt="image" src="https://github.com/imgproxy/imgproxy/assets/322057/1df3d22d-5fe3-4951-9d5f-fc1c5d9f97d2">

<img width="1284" alt="image" src="https://github.com/imgproxy/imgproxy/assets/322057/9af3b9d3-ae27-4814-823f-4ec013471d0e">

I think it may be related to these issues:

* https://github.com/davidbyttow/govips/issues/356
* https://github.com/davidbyttow/govips/issues/291

**Comment by DarthSim** [comment]
Hi @y3ti!
I believe it's because of liborc that we added to `v3.18.0`. We're working on removing it and replacing it with native SIMD instructions.

**Comment by y3ti** [comment]
I was testing the new version during last few days. I didn't observe any issues. 
Thank you @DarthSim!
