### ISSUE TITLE
Error: store of inconsistently typed value into Value

### ISSUE THREAD

**Issue by bsboris** [imgproxy/imgproxy#1292]
Hello! We regularly observe following errors, when processing video files:

```
2024/05/22 09:11:34 http: panic serving 127.0.0.1:51726: sync/atomic: store of inconsistently typed value into Value
goroutine 16289 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1898 +0xbe
panic({0x24bfc40?, 0x32975e0?})
	/usr/local/go/src/runtime/panic.go:770 +0x132
sync/atomic.(*Value).Store(0xc001ebabf0, {0x2736060, 0xc0027d4280})
	/usr/local/go/src/sync/atomic/value.go:78 +0xd5
github.com/imgproxy/imgproxy/v3/imagedata/video.videoProxyHandler({0x32bb328, 0xc0006e0d20}, 0xc001ec2c60)
	/app/imagedata/video/videoproxy.go:133 +0x868
net/http.HandlerFunc.ServeHTTP(0x475079?, {0x32bb328?, 0xc0006e0d20?}, 0xc001341b68?)
	/usr/local/go/src/net/http/server.go:2166 +0x29
net/http.serverHandler.ServeHTTP({0xc000df74d0?}, {0x32bb328?, 0xc0006e0d20?}, 0x6?)
	/usr/local/go/src/net/http/server.go:3137 +0x8e
net/http.(*conn).serve(0xc0025730e0, {0x32cb140, 0xc0009180f0})
	/usr/local/go/src/net/http/server.go:2039 +0x5e8
created by net/http.(*Server).Serve in goroutine 14
	/usr/local/go/src/net/http/server.go:3285 +0x4b4
```

It looks like something is wrong here =) Could you please take a look?

**Comment by DarthSim** [comment]
Hey @bsboris!

Fixed in the `latest` build
